package org.weather3;

import java.util.logging.Logger;
import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-10-30T21:45:18.654+08:00
 * Generated source version: 3.6.4
 */
@WebService(serviceName = "WeatherWebService", portName = "WeatherWebServiceHttpPost", targetNamespace = "http://WebXml.com.cn/", wsdlLocation = "file:/E:/study/大三上/软件体系结构/实验4/WeatherWebService_1.wsdl", endpointInterface = "WeatherWebServiceHttpPost")
public class WeatherWebServiceHttpPostImpl implements WeatherWebServiceHttpPost {

    private static final Logger LOG = Logger.getLogger(WeatherWebServiceHttpPostImpl.class.getName());

    public ArrayOfString getWeatherbyCityName(String theCityName) {
        LOG.info("Executing operation getWeatherbyCityName");
        System.out.println(theCityName);
        try {
            ArrayOfString _return = null; // Implement your logic here
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
}
