package org.weather3;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.6.4
 * 2024-10-30T21:45:18.669+08:00
 * Generated source version: 3.6.4
 */
@WebService(targetNamespace = "http://WebXml.com.cn/", name = "WeatherWebServiceHttpPost")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherWebServiceHttpPost {

    /**
     * 根据城市或地区名称查询获得未来三天内天气情况、现在的天气实况、天气和生活指数
     */
    @WebMethod
    @WebResult(name = "ArrayOfString", targetNamespace = "http://WebXml.com.cn/", partName = "Body")
    public ArrayOfString getWeatherbyCityName(
            @WebParam(partName = "theCityName", name = "theCityName", targetNamespace = "http://WebXml.com.cn/")
            java.lang.String theCityName);
}
